In [1]:
import pandas as pd
import numpy as np

In [2]:
df_gdp = pd.read_csv("../data/raw/gdp.csv", skiprows=4)

df_gdp = df_gdp[df_gdp["Country Name"] == "Sri Lanka"]

df_gdp = df_gdp.drop(columns=["Country Code", "Indicator Name", "Indicator Code"])

df_gdp_long = df_gdp.melt(id_vars=["Country Name"], var_name="Year", value_name="GDP")

df_gdp_long = df_gdp_long.rename(columns={"Country Name": "Country"})

df_gdp_long = df_gdp_long.dropna()

df_gdp_long["Year"] = df_gdp_long["Year"].astype(int)

df_gdp_long = df_gdp_long.sort_values("Year").reset_index(drop=True)

df_gdp_long.head()

     Country  Year         GDP
0  Sri Lanka  1960  145.928701
1  Sri Lanka  1961  145.900945
2  Sri Lanka  1962  141.383198
3  Sri Lanka  1963  119.352332
4  Sri Lanka  1964  122.941809

In [3]:
df_imports = pd.read_csv("../data/raw/imports.csv", skiprows=4)

df_imports = df_imports[df_imports["Country Name"] == "Sri Lanka"]

df_imports = df_imports.drop(columns=["Country Code", "Indicator Name", "Indicator Code"])

df_imports_long = df_imports.melt(id_vars=["Country Name"], var_name="Year", value_name="Imports")

df_imports_long = df_imports_long.rename(columns={"Country Name": "Country"})

df_imports_long = df_imports_long.dropna()

df_imports_long["Year"] = df_imports_long["Year"].astype(int)

df_imports_long = df_imports_long.sort_values("Year").reset_index(drop=True)

df_imports_long.head()

     Country  Year  Imports
0  Sri Lanka  2000     4.48
1  Sri Lanka  2001     3.50
2  Sri Lanka  2002     3.33
3  Sri Lanka  2003     4.64
4  Sri Lanka  2004     4.17

In [4]:
df_ewaste = pd.read_csv("../data/raw/ewaste.csv")

df_ewaste = df_ewaste[["Country", "Year", "E_Waste_Generation_Million_Metric_Tons"]]

df_ewaste = df_ewaste.rename(columns={
    "E_Waste_Generation_Million_Metric_Tons": "E_waste_MT"
})

# convert to metric tons
df_ewaste["E_waste_MT"] = df_ewaste["E_waste_MT"] * 1_000_000

# select one country (India) and map to Sri Lanka
df_ewaste = df_ewaste[df_ewaste["Country"] == "India"]
df_ewaste["Country"] = "Sri Lanka"

df_ewaste = df_ewaste.dropna()

df_ewaste = df_ewaste.sort_values("Year").reset_index(drop=True)

df_ewaste.head()

     Country  Year  E_waste_MT
0  Sri Lanka  2015   4100000.0
1  Sri Lanka  2016   4370000.0
2  Sri Lanka  2017   4750000.0
3  Sri Lanka  2018   4860000.0
4  Sri Lanka  2019   4780000.0

In [5]:
df_merge = pd.merge(df_gdp_long, df_imports_long, on=["Country", "Year"])

df_final = pd.merge(df_merge, df_ewaste, on=["Country", "Year"])

df_final = df_final.sort_values("Year").reset_index(drop=True)

df_final.head()

     Country  Year          GDP  Imports  E_waste_MT
0  Sri Lanka  2015  4057.715835     4.22   4100000.0
1  Sri Lanka  2016  4149.191908     4.95   4370000.0
2  Sri Lanka  2017  4398.888281     4.73   4750000.0
3  Sri Lanka  2019  4081.947727     4.64   4780000.0
4  Sri Lanka  2020  3847.601377     5.36   4600000.0

In [6]:
# create full year range
full_years = pd.DataFrame({
    "Year": range(df_final["Year"].min(), df_final["Year"].max() + 1)
})

df_final = pd.merge(full_years, df_final, on="Year", how="left")

# forward fill
df_final = df_final.ffill()

df_final["Country"] = "Sri Lanka"

df_final = df_final.sort_values("Year").reset_index(drop=True)

df_final.head(10)

   Year    Country          GDP  Imports  E_waste_MT
0  2015  Sri Lanka  4057.715835     4.22   4100000.0
1  2016  Sri Lanka  4149.191908     4.95   4370000.0
2  2017  Sri Lanka  4398.888281     4.73   4750000.0
3  2018  Sri Lanka  4398.888281     4.73   4750000.0
4  2019  Sri Lanka  4081.947727     4.64   4780000.0
5  2020  Sri Lanka  3847.601377     5.36   4600000.0
6  2021  Sri Lanka  3996.962400     6.20   4700000.0
7  2022  Sri Lanka  3342.636503     3.01   5040000.0

In [7]:
from sklearn.preprocessing import MinMaxScaler

features = df_final[["GDP", "Imports"]]
target = df_final[["E_waste_MT"]]

scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()

X_scaled = scaler_X.fit_transform(features)
y_scaled = scaler_y.fit_transform(target)

X_scaled_df = pd.DataFrame(X_scaled, columns=["GDP", "Imports"])
y_scaled_df = pd.DataFrame(y_scaled, columns=["E_waste_MT"])

print(X_scaled_df.head())
print(y_scaled_df.head())

        GDP   Imports
0  0.676997  0.379310
1  0.763601  0.608150
2  1.000000  0.539185
3  1.000000  0.539185
4  0.699938  0.510972
   E_waste_MT
0    0.000000
1    0.287234
2    0.691489
3    0.691489
4    0.723404

In [8]:
print(df_final.head())
print(df_final.columns)

   Year    Country          GDP  Imports  E_waste_MT
0  2015  Sri Lanka  4057.715835     4.22   4100000.0
1  2016  Sri Lanka  4149.191908     4.95   4370000.0
2  2017  Sri Lanka  4398.888281     4.73   4750000.0
3  2018  Sri Lanka  4398.888281     4.73   4750000.0
4  2019  Sri Lanka  4081.947727     4.64   4780000.0
Index(['Year', 'Country', 'GDP', 'Imports', 'E_waste_MT'], dtype='object')

In [9]:
print(df_final.isnull().sum())

Year          0
Country       0
GDP           0
Imports       0
E_waste_MT    0
dtype: int64

In [10]:
print(df_final["Year"].tolist())

[2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]

In [11]:
print(len(df_final))

8

In [12]:
print(X_scaled_df.describe())
print(y_scaled_df.describe())

            GDP   Imports
count  8.000000  8.000000
mean   0.654761  0.539185
std    0.319360  0.286153
min    0.000000  0.000000
25%    0.584127  0.478056
50%    0.688468  0.539185
75%    0.822701  0.640282
max    1.000000  1.000000
       E_waste_MT
count    8.000000
mean     0.570479
std      0.304472
min      0.000000
25%      0.470745
50%      0.664894
75%      0.699468
max      1.000000

In [13]:
print(X_scaled_df.shape)
print(y_scaled_df.shape)

(8, 2)
(8, 1)

In [14]:
# split index (80% approx)
split_index = int(len(df_final) * 0.8)

# split dataset
train = df_final.iloc[:split_index]
test = df_final.iloc[split_index:]

print("Train data:")
print(train)

print("\nTest data:")
print(test)

Train data:
   Year    Country          GDP  Imports  E_waste_MT
0  2015  Sri Lanka  4057.715835     4.22   4100000.0
1  2016  Sri Lanka  4149.191908     4.95   4370000.0
2  2017  Sri Lanka  4398.888281     4.73   4750000.0
3  2018  Sri Lanka  4398.888281     4.73   4750000.0
4  2019  Sri Lanka  4081.947727     4.64   4780000.0
5  2020  Sri Lanka  3847.601377     5.36   4600000.0

Test data:
   Year    Country          GDP  Imports  E_waste_MT
6  2021  Sri Lanka  3996.962400     6.20   4700000.0
7  2022  Sri Lanka  3342.636503     3.01   5040000.0

In [15]:
print(train["Year"].min(), train["Year"].max())
print(test["Year"].min(), test["Year"].max())

2015 2020
2021 2022

In [16]:
from sklearn.preprocessing import MinMaxScaler

# features and target
X_train = train[["GDP", "Imports"]]
X_test = test[["GDP", "Imports"]]

y_train = train[["E_waste_MT"]]
y_test = test[["E_waste_MT"]]

In [17]:
scaler_X = MinMaxScaler()
scaler_y = MinMaxScaler()

In [18]:
X_train_scaled = scaler_X.fit_transform(X_train)
y_train_scaled = scaler_y.fit_transform(y_train)

In [19]:
X_test_scaled = scaler_X.transform(X_test)
y_test_scaled = scaler_y.transform(y_test)

In [20]:
import pandas as pd

print(pd.DataFrame(X_train_scaled, columns=["GDP","Imports"]))
print(pd.DataFrame(y_train_scaled, columns=["E_waste"]))

        GDP   Imports
0  0.381134  0.000000
1  0.547066  0.640351
2  1.000000  0.447368
3  1.000000  0.447368
4  0.425090  0.368421
5  0.000000  1.000000
    E_waste
0  0.000000
1  0.397059
2  0.955882
3  0.955882
4  1.000000
5  0.735294

In [21]:
import numpy as np

def create_sequences(X, y, window_size):
    X_seq = []
    y_seq = []

    for i in range(len(X) - window_size):
        X_seq.append(X[i:i+window_size])
        y_seq.append(y[i+window_size])

    return np.array(X_seq), np.array(y_seq)

In [22]:
window_size = 3

X_train_seq, y_train_seq = create_sequences(X_train_scaled, y_train_scaled, window_size)
X_test_seq, y_test_seq = create_sequences(X_test_scaled, y_test_scaled, window_size)

In [23]:
print(X_train_seq.shape)
print(y_train_seq.shape)

(3, 3, 2)
(3, 1)

In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

ModuleNotFoundError: No module named 'tensorflow'

In [25]:
pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.21.0-cp312-cp312-win_amd64.whl.metadata (4.5 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Downloading absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Downloading astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Downloading libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in D:\softwares\Files\Python\Lib\site-packages (from tensorflow) (24.2)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in D:\softwares\Files\Python\Lib\site-packages (from tensorflow) (81.0.0)
Requirement already satisfied: six>=1.12.0 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow) (4.15.0)
Collecting wrapt>=1.11.0 (from tensorflow)
  Downloading wrapt-2.1.2-cp312-cp312-win_amd64.whl.metadata (7.6 kB)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow) (1.76.0)
Collecting keras>=3.12.0 (from tensorflow)
  Downloading keras-3.14.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow) (2.2.3)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Downloading h5py-3.14.0-cp312-cp312-win_amd64.whl.metadata (2.7 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.4-cp312-cp312-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in D:\softwares\Files\Python\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in D:\softwares\Files\Python\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in D:\softwares\Files\Python\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in D:\softwares\Files\Python\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.11.12)
Collecting wheel<1.0,>=0.23.0 (from astunparse>=1.6.0->tensorflow)
  Downloading wheel-0.47.0-py3-none-any.whl.metadata (2.3 kB)
Collecting rich (from keras>=3.12.0->tensorflow)
  Downloading rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting namex (from keras>=3.12.0->tensorflow)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow)
  Downloading optree-0.19.0-cp312-cp312-win_amd64.whl.metadata (35 kB)
Collecting markdown-it-py>=2.2.0 (from rich->keras>=3.12.0->tensorflow)
  Downloading markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in D:\softwares\Files\Python\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Downloading tensorflow-2.21.0-cp312-cp312-win_amd64.whl (350.9 MB)
   ---------------------------------------- 0.0/350.9 MB ? eta -:--:--
   ---------------------------------------- 0.5/350.9 MB 2.8 MB/s eta 0:02:06
   ---------------------------------------- 1.6/350.9 MB 5.6 MB/s eta 0:01:03
   ---------------------------------------- 1.6/350.9 MB 5.6 MB/s eta 0:01:03
   ---------------------------------------- 1.6/350.9 MB 5.6 MB/s eta 0:01:03
   ---------------------------------------- 1.8/350.9 MB 1.7 MB/s eta 0:03:25
   ---------------------------------------- 1.8/350.9 MB 1.7 MB/s eta 0:03:25
   ---------------------------------------- 2.1/350.9 MB 1.5 MB/s eta 0:03:58
   ---------------------------------------- 3.1/350.9 MB 1.9 MB/s eta 0:03:00
   ---------------------------------------- 3.1/350.9 MB 1.9 MB/s eta 0:03:00
   ---------------------------------------- 3.1/350.9 MB 1.9 MB/s eta 0:03:00
   ---------------------------------------- 3.7/350.9 MB 1.6 MB/s eta 0:03:40
    --------------------------------------- 4.5/350.9 MB 1.8 MB/s eta 0:03:12
    --------------------------------------- 4.5/350.9 MB 1.8 MB/s eta 0:03:12
    --------------------------------------- 4.7/350.9 MB 1.6 MB/s eta 0:03:35
    --------------------------------------- 5.8/350.9 MB 1.8 MB/s eta 0:03:12
    --------------------------------------- 6.0/350.9 MB 1.8 MB/s eta 0:03:10
    --------------------------------------- 6.3/350.9 MB 1.8 MB/s eta 0:03:09
    --------------------------------------- 6.3/350.9 MB 1.8 MB/s eta 0:03:09
    --------------------------------------- 6.3/350.9 MB 1.8 MB/s eta 0:03:09
    --------------------------------------- 6.6/350.9 MB 1.6 MB/s eta 0:03:38
    --------------------------------------- 7.1/350.9 MB 1.6 MB/s eta 0:03:36
    --------------------------------------- 7.6/350.9 MB 1.7 MB/s eta 0:03:28
    --------------------------------------- 7.9/350.9 MB 1.6 MB/s eta 0:03:30
    --------------------------------------- 8.4/350.9 MB 1.7 MB/s eta 0:03:25
   - -------------------------------------- 8.9/350.9 MB 1.7 MB/s eta 0:03:21
   - -------------------------------------- 9.4/350.9 MB 1.7 MB/s eta 0:03:17
   - -------------------------------------- 10.0/350.9 MB 1.8 MB/s eta 0:03:15
   - -------------------------------------- 10.5/350.9 MB 1.8 MB/s eta 0:03:11
   - -------------------------------------- 10.7/350.9 MB 1.8 MB/s eta 0:03:12
   - -------------------------------------- 11.0/350.9 MB 1.8 MB/s eta 0:03:14
   - -------------------------------------- 11.8/350.9 MB 1.8 MB/s eta 0:03:08
   - -------------------------------------- 12.1/350.9 MB 1.8 MB/s eta 0:03:07
   - -------------------------------------- 12.1/350.9 MB 1.8 MB/s eta 0:03:07
   - -------------------------------------- 12.1/350.9 MB 1.8 MB/s eta 0:03:07
   - -------------------------------------- 12.6/350.9 MB 1.7 MB/s eta 0:03:20
   - -------------------------------------- 12.8/350.9 MB 1.7 MB/s eta 0:03:18
   - -------------------------------------- 13.4/350.9 MB 1.7 MB/s eta 0:03:16
   - -------------------------------------- 13.9/350.9 MB 1.7 MB/s eta 0:03:14
   - -------------------------------------- 14.4/350.9 MB 1.8 MB/s eta 0:03:13
   - -------------------------------------- 14.9/350.9 MB 1.8 MB/s eta 0:03:10
   - -------------------------------------- 15.5/350.9 MB 1.8 MB/s eta 0:03:08
   - -------------------------------------- 16.0/350.9 MB 1.8 MB/s eta 0:03:07
   - -------------------------------------- 16.3/350.9 MB 1.8 MB/s eta 0:03:08
   - -------------------------------------- 16.5/350.9 MB 1.8 MB/s eta 0:03:08
   - -------------------------------------- 17.0/350.9 MB 1.8 MB/s eta 0:03:07
   - -------------------------------------- 17.3/350.9 MB 1.8 MB/s eta 0:03:07
   -- ------------------------------------- 17.8/350.9 MB 1.8 MB/s eta 0:03:05
   -- ------------------------------------- 18.4/350.9 MB 1.8 MB/s eta 0:03:04
   -- ------------------------------------- 18.9/350.9 MB 1.8 MB/s eta 0:03:02
   -- ------------------------------------- 19.4/350.9 MB 1.8 MB/s eta 0:03:01
   -- ------------------------------------- 19.7/350.9 MB 1.8 MB/s eta 0:03:00
   -- ------------------------------------- 20.2/350.9 MB 1.8 MB/s eta 0:03:00
   -- ------------------------------------- 20.4/350.9 MB 1.8 MB/s eta 0:03:00
   -- ------------------------------------- 21.0/350.9 MB 1.8 MB/s eta 0:03:00
   -- ------------------------------------- 21.2/350.9 MB 1.8 MB/s eta 0:03:00
   -- ------------------------------------- 21.2/350.9 MB 1.8 MB/s eta 0:03:00
   -- ------------------------------------- 21.8/350.9 MB 1.8 MB/s eta 0:03:01
   -- ------------------------------------- 22.0/350.9 MB 1.8 MB/s eta 0:03:02
   -- ------------------------------------- 22.5/350.9 MB 1.8 MB/s eta 0:03:01
   -- ------------------------------------- 22.8/350.9 MB 1.8 MB/s eta 0:03:01
   -- ------------------------------------- 23.3/350.9 MB 1.8 MB/s eta 0:03:00
   -- ------------------------------------- 23.9/350.9 MB 1.8 MB/s eta 0:02:59
   -- ------------------------------------- 24.4/350.9 MB 1.8 MB/s eta 0:02:58
   -- ------------------------------------- 24.9/350.9 MB 1.8 MB/s eta 0:02:57
   -- ------------------------------------- 25.4/350.9 MB 1.9 MB/s eta 0:02:56
   -- ------------------------------------- 26.0/350.9 MB 1.9 MB/s eta 0:02:54
   -- ------------------------------------- 26.0/350.9 MB 1.9 MB/s eta 0:02:54
   -- ------------------------------------- 26.2/350.9 MB 1.8 MB/s eta 0:02:56
   --- ------------------------------------ 26.7/350.9 MB 1.8 MB/s eta 0:02:56
   --- ------------------------------------ 27.0/350.9 MB 1.8 MB/s eta 0:02:56
   --- ------------------------------------ 27.5/350.9 MB 1.8 MB/s eta 0:02:55
   --- ------------------------------------ 28.0/350.9 MB 1.9 MB/s eta 0:02:55
   --- ------------------------------------ 28.6/350.9 MB 1.9 MB/s eta 0:02:54
   --- ------------------------------------ 29.1/350.9 MB 1.9 MB/s eta 0:02:53
   --- ------------------------------------ 29.6/350.9 MB 1.9 MB/s eta 0:02:52
   --- ------------------------------------ 30.1/350.9 MB 1.9 MB/s eta 0:02:51
   --- ------------------------------------ 30.1/350.9 MB 1.9 MB/s eta 0:02:51
   --- ------------------------------------ 30.7/350.9 MB 1.9 MB/s eta 0:02:52
   --- ------------------------------------ 30.9/350.9 MB 1.9 MB/s eta 0:02:52
   --- ------------------------------------ 31.2/350.9 MB 1.9 MB/s eta 0:02:53
   --- ------------------------------------ 31.5/350.9 MB 1.9 MB/s eta 0:02:53
   --- ------------------------------------ 32.0/350.9 MB 1.9 MB/s eta 0:02:52
   --- ------------------------------------ 32.5/350.9 MB 1.9 MB/s eta 0:02:52
   --- ------------------------------------ 32.8/350.9 MB 1.9 MB/s eta 0:02:51
   --- ------------------------------------ 33.3/350.9 MB 1.9 MB/s eta 0:02:51
   --- ------------------------------------ 33.8/350.9 MB 1.9 MB/s eta 0:02:50
   --- ------------------------------------ 34.3/350.9 MB 1.9 MB/s eta 0:02:49
   --- ------------------------------------ 34.9/350.9 MB 1.9 MB/s eta 0:02:48
   ---- ----------------------------------- 35.1/350.9 MB 1.9 MB/s eta 0:02:49
   ---- ----------------------------------- 35.4/350.9 MB 1.9 MB/s eta 0:02:49
   ---- ----------------------------------- 35.7/350.9 MB 1.9 MB/s eta 0:02:49
   ---- ----------------------------------- 36.2/350.9 MB 1.9 MB/s eta 0:02:49
   ---- ----------------------------------- 36.4/350.9 MB 1.9 MB/s eta 0:02:49
   ---- ----------------------------------- 37.0/350.9 MB 1.9 MB/s eta 0:02:48
   ---- ----------------------------------- 37.5/350.9 MB 1.9 MB/s eta 0:02:47
   ---- ----------------------------------- 38.0/350.9 MB 1.9 MB/s eta 0:02:47
   ---- ----------------------------------- 38.5/350.9 MB 1.9 MB/s eta 0:02:46
   ---- ----------------------------------- 39.1/350.9 MB 1.9 MB/s eta 0:02:45
   ---- ----------------------------------- 39.3/350.9 MB 1.9 MB/s eta 0:02:45
   ---- ----------------------------------- 39.6/350.9 MB 1.9 MB/s eta 0:02:45
   ---- ----------------------------------- 40.1/350.9 MB 1.9 MB/s eta 0:02:45
   ---- ----------------------------------- 40.4/350.9 MB 1.9 MB/s eta 0:02:45
   ---- ----------------------------------- 40.6/350.9 MB 1.9 MB/s eta 0:02:45
   ---- ----------------------------------- 41.2/350.9 MB 1.9 MB/s eta 0:02:45
   ---- ----------------------------------- 41.7/350.9 MB 1.9 MB/s eta 0:02:45
   ---- ----------------------------------- 42.2/350.9 MB 1.9 MB/s eta 0:02:44
   ---- ----------------------------------- 42.5/350.9 MB 1.9 MB/s eta 0:02:44
   ---- ----------------------------------- 43.0/350.9 MB 1.9 MB/s eta 0:02:43
   ---- ----------------------------------- 43.5/350.9 MB 1.9 MB/s eta 0:02:42
   ----- ---------------------------------- 44.0/350.9 MB 1.9 MB/s eta 0:02:42
   ----- ---------------------------------- 44.6/350.9 MB 1.9 MB/s eta 0:02:41
   ----- ---------------------------------- 44.8/350.9 MB 1.9 MB/s eta 0:02:41
   ----- ---------------------------------- 45.4/350.9 MB 1.9 MB/s eta 0:02:41
   ----- ---------------------------------- 45.9/350.9 MB 1.9 MB/s eta 0:02:40
   ----- ---------------------------------- 46.1/350.9 MB 1.9 MB/s eta 0:02:41
   ----- ---------------------------------- 46.7/350.9 MB 1.9 MB/s eta 0:02:40
   ----- ---------------------------------- 47.2/350.9 MB 1.9 MB/s eta 0:02:40
   ----- ---------------------------------- 47.7/350.9 MB 1.9 MB/s eta 0:02:39
   ----- ---------------------------------- 48.0/350.9 MB 1.9 MB/s eta 0:02:39
   ----- ---------------------------------- 48.5/350.9 MB 1.9 MB/s eta 0:02:38
   ----- ---------------------------------- 49.3/350.9 MB 1.9 MB/s eta 0:02:37
   ----- ---------------------------------- 49.8/350.9 MB 1.9 MB/s eta 0:02:36
   ----- ---------------------------------- 49.8/350.9 MB 1.9 MB/s eta 0:02:36
   ----- ---------------------------------- 50.3/350.9 MB 1.9 MB/s eta 0:02:37
   ----- ---------------------------------- 50.6/350.9 MB 1.9 MB/s eta 0:02:37
   ----- ---------------------------------- 51.1/350.9 MB 1.9 MB/s eta 0:02:37
   ----- ---------------------------------- 51.4/350.9 MB 1.9 MB/s eta 0:02:36
   ----- ---------------------------------- 51.6/350.9 MB 1.9 MB/s eta 0:02:36
   ----- ---------------------------------- 52.2/350.9 MB 1.9 MB/s eta 0:02:36
   ------ --------------------------------- 52.7/350.9 MB 1.9 MB/s eta 0:02:36
   ------ --------------------------------- 53.2/350.9 MB 1.9 MB/s eta 0:02:35
   ------ --------------------------------- 53.5/350.9 MB 1.9 MB/s eta 0:02:35
   ------ --------------------------------- 54.0/350.9 MB 1.9 MB/s eta 0:02:35
   ------ --------------------------------- 54.5/350.9 MB 1.9 MB/s eta 0:02:35
   ------ --------------------------------- 54.8/350.9 MB 1.9 MB/s eta 0:02:35
   ------ --------------------------------- 55.1/350.9 MB 1.9 MB/s eta 0:02:34
   ------ --------------------------------- 55.6/350.9 MB 1.9 MB/s eta 0:02:34
   ------ --------------------------------- 56.1/350.9 MB 1.9 MB/s eta 0:02:34
   ------ --------------------------------- 56.6/350.9 MB 1.9 MB/s eta 0:02:33
   ------ --------------------------------- 56.9/350.9 MB 1.9 MB/s eta 0:02:33
   ------ --------------------------------- 57.1/350.9 MB 1.9 MB/s eta 0:02:34
   ------ --------------------------------- 57.7/350.9 MB 1.9 MB/s eta 0:02:33
   ------ --------------------------------- 58.2/350.9 MB 1.9 MB/s eta 0:02:33
   ------ --------------------------------- 58.7/350.9 MB 1.9 MB/s eta 0:02:31
   ------ --------------------------------- 59.2/350.9 MB 1.9 MB/s eta 0:02:31
   ------ --------------------------------- 59.8/350.9 MB 1.9 MB/s eta 0:02:30
   ------ --------------------------------- 60.0/350.9 MB 1.9 MB/s eta 0:02:30
   ------ --------------------------------- 60.3/350.9 MB 2.0 MB/s eta 0:02:29
   ------ --------------------------------- 60.6/350.9 MB 1.9 MB/s eta 0:02:30
   ------ --------------------------------- 60.8/350.9 MB 1.9 MB/s eta 0:02:31
   ------ --------------------------------- 61.3/350.9 MB 2.0 MB/s eta 0:02:29
   ------- -------------------------------- 61.9/350.9 MB 2.0 MB/s eta 0:02:28
   ------- -------------------------------- 62.1/350.9 MB 1.9 MB/s eta 0:02:29
   ------- -------------------------------- 62.4/350.9 MB 2.0 MB/s eta 0:02:28
   ------- -------------------------------- 62.9/350.9 MB 2.0 MB/s eta 0:02:28
   ------- -------------------------------- 63.4/350.9 MB 2.0 MB/s eta 0:02:27
   ------- -------------------------------- 63.7/350.9 MB 2.0 MB/s eta 0:02:27
   ------- -------------------------------- 64.2/350.9 MB 1.9 MB/s eta 0:02:28
   ------- -------------------------------- 64.7/350.9 MB 2.0 MB/s eta 0:02:25
   ------- -------------------------------- 65.0/350.9 MB 2.0 MB/s eta 0:02:25
   ------- -------------------------------- 65.5/350.9 MB 2.0 MB/s eta 0:02:25
   ------- -------------------------------- 65.8/350.9 MB 2.0 MB/s eta 0:02:25
   ------- -------------------------------- 66.3/350.9 MB 2.0 MB/s eta 0:02:24
   ------- -------------------------------- 66.8/350.9 MB 2.0 MB/s eta 0:02:24
   ------- -------------------------------- 67.1/350.9 MB 2.0 MB/s eta 0:02:24
   ------- -------------------------------- 67.6/350.9 MB 2.0 MB/s eta 0:02:24
   ------- -------------------------------- 68.2/350.9 MB 2.0 MB/s eta 0:02:23
   ------- -------------------------------- 68.7/350.9 MB 2.0 MB/s eta 0:02:23
   ------- -------------------------------- 69.2/350.9 MB 2.0 MB/s eta 0:02:23
   ------- -------------------------------- 69.5/350.9 MB 2.0 MB/s eta 0:02:24
   ------- -------------------------------- 70.0/350.9 MB 2.0 MB/s eta 0:02:22
   -------- ------------------------------- 70.5/350.9 MB 2.0 MB/s eta 0:02:22
   -------- ------------------------------- 71.0/350.9 MB 2.0 MB/s eta 0:02:22
   -------- ------------------------------- 71.6/350.9 MB 2.0 MB/s eta 0:02:19
   -------- ------------------------------- 71.6/350.9 MB 2.0 MB/s eta 0:02:19
   -------- ------------------------------- 71.6/350.9 MB 2.0 MB/s eta 0:02:19
   -------- ------------------------------- 72.1/350.9 MB 2.0 MB/s eta 0:02:21
   -------- ------------------------------- 72.4/350.9 MB 2.0 MB/s eta 0:02:21
   -------- ------------------------------- 72.9/350.9 MB 2.0 MB/s eta 0:02:20
   -------- ------------------------------- 73.4/350.9 MB 2.0 MB/s eta 0:02:20
   -------- ------------------------------- 73.9/350.9 MB 2.0 MB/s eta 0:02:20
   -------- ------------------------------- 74.2/350.9 MB 2.0 MB/s eta 0:02:20
   -------- ------------------------------- 74.7/350.9 MB 2.0 MB/s eta 0:02:20
   -------- ------------------------------- 75.2/350.9 MB 2.0 MB/s eta 0:02:19
   -------- ------------------------------- 75.5/350.9 MB 2.0 MB/s eta 0:02:19
   -------- ------------------------------- 75.8/350.9 MB 2.0 MB/s eta 0:02:19
   -------- ------------------------------- 76.3/350.9 MB 2.0 MB/s eta 0:02:19
   -------- ------------------------------- 76.8/350.9 MB 2.0 MB/s eta 0:02:19
   -------- ------------------------------- 77.1/350.9 MB 2.0 MB/s eta 0:02:19
   -------- ------------------------------- 77.6/350.9 MB 2.0 MB/s eta 0:02:18
   -------- ------------------------------- 78.1/350.9 MB 2.0 MB/s eta 0:02:18
   -------- ------------------------------- 78.6/350.9 MB 2.0 MB/s eta 0:02:18
   -------- ------------------------------- 78.9/350.9 MB 2.0 MB/s eta 0:02:18
   --------- ------------------------------ 79.4/350.9 MB 2.0 MB/s eta 0:02:17
   --------- ------------------------------ 79.7/350.9 MB 2.0 MB/s eta 0:02:17
   --------- ------------------------------ 80.2/350.9 MB 2.0 MB/s eta 0:02:17
   --------- ------------------------------ 80.5/350.9 MB 2.0 MB/s eta 0:02:17
   --------- ------------------------------ 81.0/350.9 MB 2.0 MB/s eta 0:02:16
   --------- ------------------------------ 81.5/350.9 MB 2.0 MB/s eta 0:02:16
   --------- ------------------------------ 81.8/350.9 MB 2.0 MB/s eta 0:02:15
   --------- ------------------------------ 82.3/350.9 MB 2.0 MB/s eta 0:02:15

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
googleapis-common-protos 1.72.0 requires protobuf!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.20.2, but you have protobuf 7.34.1 which is incompatible.
google-ai-generativelanguage 0.6.15 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2, but you have protobuf 7.34.1 which is incompatible.
google-api-core 2.28.1 requires protobuf!=3.20.0,!=3.20.1,!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<7.0.0,>=3.19.5, but you have protobuf 7.34.1 which is incompatible.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 7.34.1 which is incompatible.
proto-plus 1.27.0 requires protobuf<7.0.0,>=3.19.0, but you have protobuf 7.34.1 which is incompatible.

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: D:\softwares\Files\Python\python.exe -m pip install --upgrade pip

In [26]:
pip install tensorflow==2.16.1

Collecting tensorflow==2.16.1
  Downloading tensorflow-2.16.1-cp312-cp312-win_amd64.whl.metadata (3.5 kB)
Collecting tensorflow-intel==2.16.1 (from tensorflow==2.16.1)
  Downloading tensorflow_intel-2.16.1-cp312-cp312-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: absl-py>=1.0.0 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (0.2.0)
Requirement already satisfied: h5py>=3.10.0 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (3.14.0)
Requirement already satisfied: libclang>=13.0.0 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (18.1.1)
Collecting ml-dtypes~=0.3.1 (from tensorflow-intel==2.16.1->tensorflow==2.16.1)
  Downloading ml_dtypes-0.3.2-cp312-cp312-win_amd64.whl.metadata (20 kB)
Requirement already satisfied: opt-einsum>=2.3.2 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (3.4.0)
Requirement already satisfied: packaging in D:\softwares\Files\Python\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (24.2)
Collecting protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 (from tensorflow-intel==2.16.1->tensorflow==2.16.1)
  Downloading protobuf-4.25.9-cp310-abi3-win_amd64.whl.metadata (541 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (2.32.5)
Requirement already satisfied: setuptools in D:\softwares\Files\Python\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (81.0.0)
Requirement already satisfied: six>=1.12.0 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (1.76.0)
Collecting tensorboard<2.17,>=2.16 (from tensorflow-intel==2.16.1->tensorflow==2.16.1)
  Downloading tensorboard-2.16.2-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: keras>=3.0.0 in D:\softwares\Files\Python\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (3.14.0)
Collecting numpy<2.0.0,>=1.26.0 (from tensorflow-intel==2.16.1->tensorflow==2.16.1)
  Downloading numpy-1.26.4-cp312-cp312-win_amd64.whl.metadata (61 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in D:\softwares\Files\Python\Lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in D:\softwares\Files\Python\Lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in D:\softwares\Files\Python\Lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in D:\softwares\Files\Python\Lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (2025.11.12)
Collecting markdown>=2.6.8 (from tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow==2.16.1)
  Downloading markdown-3.10.2-py3-none-any.whl.metadata (5.1 kB)
Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow==2.16.1)
  Downloading tensorboard_data_server-0.7.2-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: werkzeug>=1.0.1 in D:\softwares\Files\Python\Lib\site-packages (from tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow==2.16.1) (3.1.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in D:\softwares\Files\Python\Lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (0.47.0)
Requirement already satisfied: rich in D:\softwares\Files\Python\Lib\site-packages (from keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (15.0.0)
Requirement already satisfied: namex in D:\softwares\Files\Python\Lib\site-packages (from keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (0.1.0)
Requirement already satisfied: optree in D:\softwares\Files\Python\Lib\site-packages (from keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (0.19.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in D:\softwares\Files\Python\Lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow==2.16.1) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in D:\softwares\Files\Python\Lib\site-packages (from rich->keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in D:\softwares\Files\Python\Lib\site-packages (from rich->keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in D:\softwares\Files\Python\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (0.1.2)
Downloading tensorflow-2.16.1-cp312-cp312-win_amd64.whl (2.1 kB)
Downloading tensorflow_intel-2.16.1-cp312-cp312-win_amd64.whl (377.1 MB)
   ---------------------------------------- 0.0/377.1 MB ? eta -:--:--
   ---------------------------------------- 1.0/377.1 MB 10.1 MB/s eta 0:00:38
   ---------------------------------------- 1.0/377.1 MB 10.1 MB/s eta 0:00:38
   ---------------------------------------- 1.3/377.1 MB 1.9 MB/s eta 0:03:17
   ---------------------------------------- 2.1/377.1 MB 2.6 MB/s eta 0:02:27
   ---------------------------------------- 2.1/377.1 MB 2.6 MB/s eta 0:02:27
   ---------------------------------------- 2.1/377.1 MB 2.6 MB/s eta 0:02:27
   ---------------------------------------- 3.4/377.1 MB 2.4 MB/s eta 0:02:36
   ---------------------------------------- 3.4/377.1 MB 2.4 MB/s eta 0:02:36
   ---------------------------------------- 3.4/377.1 MB 2.4 MB/s eta 0:02:36
   ---------------------------------------- 4.2/377.1 MB 2.0 MB/s eta 0:03:09
    --------------------------------------- 5.8/377.1 MB 2.5 MB/s eta 0:02:27
    --------------------------------------- 5.8/377.1 MB 2.5 MB/s eta 0:02:27
    --------------------------------------- 5.8/377.1 MB 2.5 MB/s eta 0:02:27
    --------------------------------------- 5.8/377.1 MB 2.5 MB/s eta 0:02:27
    --------------------------------------- 5.8/377.1 MB 2.5 MB/s eta 0:02:27
    --------------------------------------- 6.6/377.1 MB 1.9 MB/s eta 0:03:11
    --------------------------------------- 7.9/377.1 MB 2.3 MB/s eta 0:02:44
    --------------------------------------- 7.9/377.1 MB 2.3 MB/s eta 0:02:44
    --------------------------------------- 7.9/377.1 MB 2.3 MB/s eta 0:02:44
    --------------------------------------- 7.9/377.1 MB 2.3 MB/s eta 0:02:44
    --------------------------------------- 7.9/377.1 MB 2.3 MB/s eta 0:02:44
    --------------------------------------- 8.9/377.1 MB 1.9 MB/s eta 0:03:13
    --------------------------------------- 9.2/377.1 MB 1.9 MB/s eta 0:03:10
    --------------------------------------- 9.2/377.1 MB 1.9 MB/s eta 0:03:10
   - -------------------------------------- 9.4/377.1 MB 1.8 MB/s eta 0:03:25
   - -------------------------------------- 10.2/377.1 MB 1.8 MB/s eta 0:03:19
   - -------------------------------------- 11.5/377.1 MB 2.0 MB/s eta 0:03:02
   - -------------------------------------- 11.5/377.1 MB 2.0 MB/s eta 0:03:02
   - -------------------------------------- 11.5/377.1 MB 2.0 MB/s eta 0:03:02
   - -------------------------------------- 11.5/377.1 MB 2.0 MB/s eta 0:03:02
   - -------------------------------------- 11.8/377.1 MB 1.8 MB/s eta 0:03:23
   - -------------------------------------- 12.3/377.1 MB 1.8 MB/s eta 0:03:20
   - -------------------------------------- 13.1/377.1 MB 1.9 MB/s eta 0:03:13
   - -------------------------------------- 13.1/377.1 MB 1.9 MB/s eta 0:03:13
   - -------------------------------------- 13.1/377.1 MB 1.9 MB/s eta 0:03:13
   - -------------------------------------- 13.1/377.1 MB 1.9 MB/s eta 0:03:13
   - -------------------------------------- 13.9/377.1 MB 1.8 MB/s eta 0:03:24
   - -------------------------------------- 14.7/377.1 MB 1.8 MB/s eta 0:03:19
   - -------------------------------------- 14.7/377.1 MB 1.8 MB/s eta 0:03:19
   - -------------------------------------- 14.7/377.1 MB 1.8 MB/s eta 0:03:19
   - -------------------------------------- 14.7/377.1 MB 1.8 MB/s eta 0:03:19
   - -------------------------------------- 14.9/377.1 MB 1.7 MB/s eta 0:03:34
   - -------------------------------------- 15.5/377.1 MB 1.7 MB/s eta 0:03:31
   - -------------------------------------- 16.0/377.1 MB 1.7 MB/s eta 0:03:29
   - -------------------------------------- 16.0/377.1 MB 1.7 MB/s eta 0:03:29
   - -------------------------------------- 16.5/377.1 MB 1.7 MB/s eta 0:03:31
   - -------------------------------------- 17.0/377.1 MB 1.7 MB/s eta 0:03:29
   - -------------------------------------- 17.6/377.1 MB 1.7 MB/s eta 0:03:27
   - -------------------------------------- 18.1/377.1 MB 1.8 MB/s eta 0:03:25
   - -------------------------------------- 18.6/377.1 MB 1.8 MB/s eta 0:03:23
   -- ------------------------------------- 19.1/377.1 MB 1.8 MB/s eta 0:03:21
   -- ------------------------------------- 19.1/377.1 MB 1.8 MB/s eta 0:03:21
   -- ------------------------------------- 19.4/377.1 MB 1.7 MB/s eta 0:03:27
   -- ------------------------------------- 19.7/377.1 MB 1.7 MB/s eta 0:03:27
   -- ------------------------------------- 19.9/377.1 MB 1.7 MB/s eta 0:03:29
   -- ------------------------------------- 20.4/377.1 MB 1.7 MB/s eta 0:03:27
   -- ------------------------------------- 20.7/377.1 MB 1.7 MB/s eta 0:03:27
   -- ------------------------------------- 21.2/377.1 MB 1.7 MB/s eta 0:03:25
   -- ------------------------------------- 21.8/377.1 MB 1.8 MB/s eta 0:03:23
   -- ------------------------------------- 22.0/377.1 MB 1.8 MB/s eta 0:03:23
   -- ------------------------------------- 22.5/377.1 MB 1.8 MB/s eta 0:03:23
   -- ------------------------------------- 23.1/377.1 MB 1.8 MB/s eta 0:03:22
   -- ------------------------------------- 23.3/377.1 MB 1.8 MB/s eta 0:03:21
   -- ------------------------------------- 23.9/377.1 MB 1.8 MB/s eta 0:03:20
   -- ------------------------------------- 24.4/377.1 MB 1.8 MB/s eta 0:03:19
   -- ------------------------------------- 24.9/377.1 MB 1.8 MB/s eta 0:03:17
   -- ------------------------------------- 25.4/377.1 MB 1.8 MB/s eta 0:03:16
   -- ------------------------------------- 26.0/377.1 MB 1.8 MB/s eta 0:03:14
   -- ------------------------------------- 26.0/377.1 MB 1.8 MB/s eta 0:03:14
   -- ------------------------------------- 26.2/377.1 MB 1.8 MB/s eta 0:03:18
   -- ------------------------------------- 26.5/377.1 MB 1.8 MB/s eta 0:03:18
   -- ------------------------------------- 27.0/377.1 MB 1.8 MB/s eta 0:03:17
   -- ------------------------------------- 27.5/377.1 MB 1.8 MB/s eta 0:03:16
   -- ------------------------------------- 27.8/377.1 MB 1.8 MB/s eta 0:03:16
   -- ------------------------------------- 28.0/377.1 MB 1.8 MB/s eta 0:03:17
   --- ------------------------------------ 28.8/377.1 MB 1.8 MB/s eta 0:03:15
   --- ------------------------------------ 29.4/377.1 MB 1.8 MB/s eta 0:03:14
   --- ------------------------------------ 29.9/377.1 MB 1.8 MB/s eta 0:03:12
   --- ------------------------------------ 29.9/377.1 MB 1.8 MB/s eta 0:03:12
   --- ------------------------------------ 29.9/377.1 MB 1.8 MB/s eta 0:03:12
   --- ------------------------------------ 30.1/377.1 MB 1.8 MB/s eta 0:03:16
   --- ------------------------------------ 30.4/377.1 MB 1.8 MB/s eta 0:03:17
   --- ------------------------------------ 30.7/377.1 MB 1.8 MB/s eta 0:03:18
   --- ------------------------------------ 31.2/377.1 MB 1.8 MB/s eta 0:03:17
   --- ------------------------------------ 31.7/377.1 MB 1.8 MB/s eta 0:03:16
   --- ------------------------------------ 32.0/377.1 MB 1.8 MB/s eta 0:03:16
   --- ------------------------------------ 32.5/377.1 MB 1.8 MB/s eta 0:03:15
   --- ------------------------------------ 33.0/377.1 MB 1.8 MB/s eta 0:03:14
   --- ------------------------------------ 33.6/377.1 MB 1.8 MB/s eta 0:03:13
   --- ------------------------------------ 34.1/377.1 MB 1.8 MB/s eta 0:03:12
   --- ------------------------------------ 34.3/377.1 MB 1.8 MB/s eta 0:03:13
   --- ------------------------------------ 34.3/377.1 MB 1.8 MB/s eta 0:03:13
   --- ------------------------------------ 34.9/377.1 MB 1.8 MB/s eta 0:03:14
   --- ------------------------------------ 35.1/377.1 MB 1.8 MB/s eta 0:03:14
   --- ------------------------------------ 35.1/377.1 MB 1.8 MB/s eta 0:03:14
   --- ------------------------------------ 35.7/377.1 MB 1.8 MB/s eta 0:03:15
   --- ------------------------------------ 36.2/377.1 MB 1.8 MB/s eta 0:03:14
   --- ------------------------------------ 36.7/377.1 MB 1.8 MB/s eta 0:03:13
   --- ------------------------------------ 37.0/377.1 MB 1.8 MB/s eta 0:03:13
   --- ------------------------------------ 37.5/377.1 MB 1.8 MB/s eta 0:03:12
   ---- ----------------------------------- 37.7/377.1 MB 1.8 MB/s eta 0:03:12
   ---- ----------------------------------- 38.3/377.1 MB 1.8 MB/s eta 0:03:11
   ---- ----------------------------------- 38.8/377.1 MB 1.8 MB/s eta 0:03:11
   ---- ----------------------------------- 39.3/377.1 MB 1.8 MB/s eta 0:03:10
   ---- ----------------------------------- 39.6/377.1 MB 1.8 MB/s eta 0:03:10
   ---- ----------------------------------- 40.1/377.1 MB 1.8 MB/s eta 0:03:09
   ---- ----------------------------------- 40.6/377.1 MB 1.8 MB/s eta 0:03:07
   ---- ----------------------------------- 40.9/377.1 MB 1.8 MB/s eta 0:03:07
   ---- ----------------------------------- 41.2/377.1 MB 1.8 MB/s eta 0:03:08
   ---- ----------------------------------- 41.4/377.1 MB 1.8 MB/s eta 0:03:08
   ---- ----------------------------------- 41.7/377.1 MB 1.8 MB/s eta 0:03:09
   ---- ----------------------------------- 42.2/377.1 MB 1.8 MB/s eta 0:03:08
   ---- ----------------------------------- 42.7/377.1 MB 1.8 MB/s eta 0:03:07
   ---- ----------------------------------- 43.3/377.1 MB 1.8 MB/s eta 0:03:06
   ---- ----------------------------------- 43.8/377.1 MB 1.8 MB/s eta 0:03:06
   ---- ----------------------------------- 44.0/377.1 MB 1.8 MB/s eta 0:03:05
   ---- ----------------------------------- 44.6/377.1 MB 1.8 MB/s eta 0:03:05
   ---- ----------------------------------- 44.8/377.1 MB 1.8 MB/s eta 0:03:05
   ---- ----------------------------------- 45.4/377.1 MB 1.8 MB/s eta 0:03:04
   ---- ----------------------------------- 45.9/377.1 MB 1.8 MB/s eta 0:03:04
   ---- ----------------------------------- 46.1/377.1 MB 1.8 MB/s eta 0:03:03
   ---- ----------------------------------- 46.7/377.1 MB 1.8 MB/s eta 0:03:03
   ----- ---------------------------------- 47.2/377.1 MB 1.8 MB/s eta 0:03:02
   ----- ---------------------------------- 47.7/377.1 MB 1.8 MB/s eta 0:03:01
   ----- ---------------------------------- 48.0/377.1 MB 1.8 MB/s eta 0:03:01
   ----- ---------------------------------- 48.5/377.1 MB 1.8 MB/s eta 0:03:01
   ----- ---------------------------------- 49.3/377.1 MB 1.8 MB/s eta 0:02:59
   ----- ---------------------------------- 49.3/377.1 MB 1.8 MB/s eta 0:02:59
   ----- ---------------------------------- 49.3/377.1 MB 1.8 MB/s eta 0:02:59
   ----- ---------------------------------- 49.8/377.1 MB 1.8 MB/s eta 0:03:01
   ----- ---------------------------------- 50.3/377.1 MB 1.8 MB/s eta 0:03:00
   ----- ---------------------------------- 50.9/377.1 MB 1.8 MB/s eta 0:03:00
   ----- ---------------------------------- 51.4/377.1 MB 1.8 MB/s eta 0:02:59
   ----- ---------------------------------- 51.9/377.1 MB 1.8 MB/s eta 0:02:58
   ----- ---------------------------------- 52.2/377.1 MB 1.8 MB/s eta 0:02:58
   ----- ---------------------------------- 52.4/377.1 MB 1.8 MB/s eta 0:02:58
   ----- ---------------------------------- 52.7/377.1 MB 1.8 MB/s eta 0:02:59
   ----- ---------------------------------- 53.0/377.1 MB 1.8 MB/s eta 0:02:59
   ----- ---------------------------------- 53.5/377.1 MB 1.8 MB/s eta 0:02:58
   ----- ---------------------------------- 54.0/377.1 MB 1.8 MB/s eta 0:02:58
   ----- ---------------------------------- 54.3/377.1 MB 1.8 MB/s eta 0:02:58
   ----- ---------------------------------- 54.8/377.1 MB 1.8 MB/s eta 0:02:57
   ----- ---------------------------------- 55.3/377.1 MB 1.8 MB/s eta 0:02:58
   ----- ---------------------------------- 55.8/377.1 MB 1.8 MB/s eta 0:02:56
   ----- ---------------------------------- 56.4/377.1 MB 1.8 MB/s eta 0:02:55
   ------ --------------------------------- 56.9/377.1 MB 1.8 MB/s eta 0:02:54
   ------ --------------------------------- 57.1/377.1 MB 1.8 MB/s eta 0:02:54
   ------ --------------------------------- 57.7/377.1 MB 1.8 MB/s eta 0:02:54
   ------ --------------------------------- 57.7/377.1 MB 1.8 MB/s eta 0:02:54
   ------ --------------------------------- 57.9/377.1 MB 1.8 MB/s eta 0:02:55
   ------ --------------------------------- 58.5/377.1 MB 1.8 MB/s eta 0:02:55
   ------ --------------------------------- 59.0/377.1 MB 1.8 MB/s eta 0:02:56
   ------ --------------------------------- 59.5/377.1 MB 1.8 MB/s eta 0:02:53
   ------ --------------------------------- 60.0/377.1 MB 1.8 MB/s eta 0:02:52
   ------ --------------------------------- 60.0/377.1 MB 1.8 MB/s eta 0:02:52
   ------ --------------------------------- 60.3/377.1 MB 1.8 MB/s eta 0:02:54
   ------ --------------------------------- 60.6/377.1 MB 1.8 MB/s eta 0:02:54
   ------ --------------------------------- 60.8/377.1 MB 1.8 MB/s eta 0:02:55
   ------ --------------------------------- 61.3/377.1 MB 1.8 MB/s eta 0:02:53
   ------ --------------------------------- 61.9/377.1 MB 1.8 MB/s eta 0:02:53
   ------ --------------------------------- 62.1/377.1 MB 1.8 MB/s eta 0:02:53
   ------ --------------------------------- 62.7/377.1 MB 1.8 MB/s eta 0:02:52
   ------ --------------------------------- 63.2/377.1 MB 1.8 MB/s eta 0:02:51
   ------ --------------------------------- 63.4/377.1 MB 1.8 MB/s eta 0:02:54
   ------ --------------------------------- 64.0/377.1 MB 1.8 MB/s eta 0:02:51
   ------ --------------------------------- 64.5/377.1 MB 1.8 MB/s eta 0:02:50
   ------ --------------------------------- 64.7/377.1 MB 1.8 MB/s eta 0:02:50
   ------ --------------------------------- 65.0/377.1 MB 1.8 MB/s eta 0:02:51
   ------ --------------------------------- 65.3/377.1 MB 1.8 MB/s eta 0:02:54
   ------ --------------------------------- 65.8/377.1 MB 1.8 MB/s eta 0:02:50
   ------- -------------------------------- 66.3/377.1 MB 1.8 MB/s eta 0:02:50

WARNING: Attempting to resume incomplete download (181.0 MB/377.1 MB, attempt 1)
  WARNING: Failed to remove contents in a temporary directory 'D:\softwares\Files\Python\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'D:\softwares\Files\Python\Lib\site-packages\~umpy'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
grpcio-status 1.71.2 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 4.25.9 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.

[notice] A new release of pip is available: 26.0.1 -> 26.1
[notice] To update, run: D:\softwares\Files\Python\python.exe -m pip install --upgrade pip

In [1]:
import tensorflow as tf
print(tf.__version__)

AttributeError: module 'tensorflow' has no attribute '__version__'

In [1]:
import tensorflow as tf
print(tf.__version__)

2.16.1

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

In [3]:
model = Sequential()

model.add(LSTM(50, activation='relu', input_shape=(3, 2)))
model.add(Dense(1))

model.summary()

D:\Work\04_Y4S1\03_RP\Research\new component 2\project\e_waste_project\ml\venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                          │ (None, 50)                  │          10,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │              51 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 10,651 (41.61 KB)

 Trainable params: 10,651 (41.61 KB)

 Non-trainable params: 0 (0.00 B)

In [37]:
model.compile(optimizer='adam', loss='mse')

In [38]:
history = model.fit(
    X_train_seq, y_train_seq,
    epochs=30,
    verbose=1
)

Epoch 1/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step - loss: 0.1003
Epoch 2/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - loss: 0.0915
Epoch 3/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - loss: 0.0832
Epoch 4/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - loss: 0.0753
Epoch 5/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - loss: 0.0679
Epoch 6/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - loss: 0.0610
Epoch 7/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 170ms/step - loss: 0.0547
Epoch 8/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - loss: 0.0489
Epoch 9/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 174ms/step - loss: 0.0438
Epoch 10/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step - loss: 0.0394
Epoch 11/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 224ms/step - loss: 0.0358
Epoch 12/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 159ms/step - loss: 0.0328
Epoch 13/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - loss: 0.0306
Epoch 14/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step - loss: 0.0291
Epoch 15/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - loss: 0.0283
Epoch 16/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - loss: 0.0280
Epoch 17/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - loss: 0.0281
Epoch 18/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - loss: 0.0286
Epoch 19/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step - loss: 0.0292
Epoch 20/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step - loss: 0.0298
Epoch 21/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - loss: 0.0303
Epoch 22/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 162ms/step - loss: 0.0306
Epoch 23/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step - loss: 0.0307
Epoch 24/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step - loss: 0.0306
Epoch 25/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - loss: 0.0302
Epoch 26/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 0.0297
Epoch 27/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 0.0291
Epoch 28/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 183ms/step - loss: 0.0284
Epoch 29/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 184ms/step - loss: 0.0277
Epoch 30/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step - loss: 0.0270

In [39]:
print(X_train_seq.shape)
print(y_train_seq.shape)

(3, 3, 2)
(3, 1)

In [40]:
y_pred = model.predict(X_train_seq)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 611ms/step

In [41]:
y_pred_actual = scaler_y.inverse_transform(y_pred)
y_actual = scaler_y.inverse_transform(y_train_seq)

In [42]:
for i in range(len(y_pred_actual)):
    print(f"Predicted: {y_pred_actual[i][0]:.2f} | Actual: {y_actual[i][0]:.2f}")

Predicted: 4623138.50 | Actual: 4750000.00
Predicted: 4779196.00 | Actual: 4780000.00
Predicted: 4743537.00 | Actual: 4600000.00

In [43]:
from tensorflow.keras.layers import Bidirectional

In [44]:
model = Sequential()

model.add(Bidirectional(LSTM(50, activation='relu'), input_shape=(3, 2)))
model.add(Dense(1))

model.summary()

D:\Work\04_Y4S1\03_RP\Research\new component 2\project\e_waste_project\ml\venv\Lib\site-packages\keras\src\layers\rnn\bidirectional.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ bidirectional (Bidirectional)        │ (None, 100)                 │          21,200 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 1)                   │             101 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 21,301 (83.21 KB)

 Trainable params: 21,301 (83.21 KB)

 Non-trainable params: 0 (0.00 B)

In [45]:
model.compile(optimizer='adam', loss='mse')

history = model.fit(
    X_train_seq, y_train_seq,
    epochs=30,
    verbose=1
)

Epoch 1/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 8s 8s/step - loss: 1.0525
Epoch 2/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 1.0258
Epoch 3/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 136ms/step - loss: 0.9998
Epoch 4/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - loss: 0.9744
Epoch 5/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 0.9498
Epoch 6/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - loss: 0.9259
Epoch 7/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 0.9027
Epoch 8/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - loss: 0.8805
Epoch 9/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 0.8585
Epoch 10/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - loss: 0.8368
Epoch 11/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - loss: 0.8153
Epoch 12/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 176ms/step - loss: 0.7939
Epoch 13/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step - loss: 0.7729
Epoch 14/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - loss: 0.7522
Epoch 15/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 178ms/step - loss: 0.7319
Epoch 16/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - loss: 0.7119
Epoch 17/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 148ms/step - loss: 0.6921
Epoch 18/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 173ms/step - loss: 0.6722
Epoch 19/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 0.6525
Epoch 20/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 181ms/step - loss: 0.6328
Epoch 21/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - loss: 0.6132
Epoch 22/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - loss: 0.5938
Epoch 23/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - loss: 0.5746
Epoch 24/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - loss: 0.5555
Epoch 25/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 164ms/step - loss: 0.5366
Epoch 26/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 168ms/step - loss: 0.5178
Epoch 27/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - loss: 0.4992
Epoch 28/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - loss: 0.4807
Epoch 29/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 0.4623
Epoch 30/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 0.4440