In [1]:
import pandas as pd

In [12]:
import pandas as pd

df = pd.read_csv("../data/raw/gdp.csv")

print(df.columns)

Index(['Data Source', 'World Development Indicators', 'Unnamed: 2',
       'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7',
       'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16',
       'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28',
       'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32',
       'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36',
       'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40',
       'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44',
       'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48',
       'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52',
       'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56',
       'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60',
       'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64',
       'Unnamed: 65', 'Unnamed: 66', 'Unnamed: 67', 'Unnamed: 68',
       'Unnamed: 69'],
      dtype='object')

In [13]:
import pandas as pd

# read CSV, skip first 4 rows
df = pd.read_csv("../data/raw/gdp.csv", skiprows=4)

# check columns again
print(df.columns)

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', '2025'],
      dtype='object')

In [14]:
# keep only Sri Lanka
df = df[df["Country Name"] == "Sri Lanka"]

# drop extra columns
df = df.drop(columns=["Country Code", "Indicator Name", "Indicator Code"])

# convert to long format
df_long = df.melt(id_vars=["Country Name"], var_name="Year", value_name="GDP")

# rename
df_long = df_long.rename(columns={"Country Name": "Country"})

# remove missing
df_long = df_long.dropna()

# fix year type
df_long["Year"] = df_long["Year"].astype(int)

df_long.head()

     Country  Year         GDP
0  Sri Lanka  1960  145.928701
1  Sri Lanka  1961  145.900945
2  Sri Lanka  1962  141.383198
3  Sri Lanka  1963  119.352332
4  Sri Lanka  1964  122.941809

In [15]:
df = pd.read_csv("../data/raw/gdp.csv", skiprows=4)
print(df.columns)

Index(['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code',
       '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968',
       '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977',
       '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986',
       '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995',
       '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004',
       '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013',
       '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022',
       '2023', '2024', '2025'],
      dtype='object')

In [16]:
# load data
df3 = pd.read_csv("../data/raw/ewaste.csv")

# select required columns
df3 = df3[["Country", "Year", "E_Waste_Generation_Million_Metric_Tons"]]

# rename columns
df3 = df3.rename(columns={
    "E_Waste_Generation_Million_Metric_Tons": "E_waste_MT"
})

# convert to metric tons
df3["E_waste_MT"] = df3["E_waste_MT"] * 1_000_000

# remove missing values
df3 = df3.dropna()

# sort
df3 = df3.sort_values("Year")

df3.head()

          Country  Year  E_waste_MT
0           China  2015   5570000.0
10  United States  2015   4540000.0
30        Germany  2015   2720000.0
20          India  2015   4100000.0
50          Japan  2015   4800000.0

In [17]:
# select one country
df3 = df3[df3["Country"] == "India"]

# rename to match other datasets
df3["Country"] = "Sri Lanka"

df3.head()

      Country  Year  E_waste_MT
20  Sri Lanka  2015   4100000.0
21  Sri Lanka  2016   4370000.0
22  Sri Lanka  2017   4750000.0
23  Sri Lanka  2018   4860000.0
24  Sri Lanka  2019   4780000.0

In [18]:
print(df_long["Year"].min(), df_long["Year"].max())
print(df2_long["Year"].min(), df2_long["Year"].max())
print(df3["Year"].min(), df3["Year"].max())

1960 2024

NameError: name 'df2_long' is not defined

In [19]:
df_merge = pd.merge(df_long, df2_long, on=["Country", "Year"])
df_final = pd.merge(df_merge, df3, on=["Country", "Year"])

df_final.head()

NameError: name 'df2_long' is not defined

In [20]:
# merge GDP + Imports
df_merge = pd.merge(df_long, df2_long, on=["Country", "Year"])

# merge with E-waste
df_final = pd.merge(df_merge, df3, on=["Country", "Year"])

df_final.head()

NameError: name 'df2_long' is not defined